#!/bin/bash
# Deploy Grafana Alloy on every node and ship host metrics to Grafana Cloud.
#
# Reads the token from /root/hp/alloy-token (never echoed, never passed on a command line).
# Each node's config is generated locally and copied up, then deleted from the transfer
# path: shipping a heredoc over ssh via `declare -f` indentation breaks the EOF terminator,
# and a broken alloy config fails silently.
set -uo pipefail
TOKEN_FILE=/root/hp/alloy-token
USER_ID=3619744
PUSH_URL="https://prometheus-prod-58-prod-eu-central-0.grafana.net/api/prom/push"
NODES="sensor1 sensor2 sensor3 sensor4 sensor5 sensor6 sensor7 sensor8 sensor9"

[ -s "$TOKEN_FILE" ] || { echo "STOP: no token at $TOKEN_FILE"; exit 1; }
TOKEN=$(tr -d '\n\r ' < "$TOKEN_FILE")
[ -n "$TOKEN" ] || { echo "STOP: token file blank"; exit 1; }
echo "token loaded (${#TOKEN} chars, value withheld)"

INSTALL='install -d -m 755 /etc/apt/keyrings
if [ ! -s /etc/apt/keyrings/grafana.gpg ]; then curl -fsSL https://apt.grafana.com/gpg.key | gpg --dearmor > /etc/apt/keyrings/grafana.gpg; fi
echo "deb [signed-by=/etc/apt/keyrings/grafana.gpg] https://apt.grafana.com stable main" > /etc/apt/sources.list.d/grafana.list
apt-get update -qq >/dev/null 2>&1
DEBIAN_FRONTEND=noninteractive apt-get install -y -qq alloy >/dev/null 2>&1
command -v alloy >/dev/null 2>&1 && echo alloy-ok || echo ALLOY-INSTALL-FAILED'

gen_config() {   # $1 = node name
  cat > "/root/hp/.alloy-$1.alloy" <<EOF
// Host metrics for the fleet. Generated by /root/hp/90-deploy-alloy.sh — do not hand-edit.
prometheus.exporter.unix "host" { }

discovery.relabel "host" {
  targets = prometheus.exporter.unix.host.targets

  rule {
    source_labels = ["__address__"]
    target_label  = "node"
    replacement   = "$1"
  }
}

prometheus.scrape "host" {
  targets         = discovery.relabel.host.output
  forward_to      = [prometheus.remote_write.cloud.receiver]
  scrape_interval = "30s"
  job_name        = "node"
}

prometheus.remote_write "cloud" {
  endpoint {
    url = "$PUSH_URL"
    basic_auth {
      username = "$USER_ID"
      password = "$TOKEN"
    }
  }
}
EOF
  chmod 600 "/root/hp/.alloy-$1.alloy"
}

activate_cmd() {   # $1 = remote path of the staged config
  printf 'install -o root -g alloy -m 640 %s /etc/alloy/config.alloy; systemctl enable alloy >/dev/null 2>&1; systemctl restart alloy; sleep 5; printf "service=%%s " "$(systemctl is-active alloy)"; curl -s -m 8 http://127.0.0.1:12345/-/ready >/dev/null 2>&1 && printf "ui=ready" || printf "ui=pending"' "$1"
}

for n in $NODES; do
  printf "=== %-9s " "$n"
  gen_config "$n"
  case "$n" in
    sensor1)
      eval "$INSTALL" | tr -d '\n'; printf " | "
      install -o root -g alloy -m 640 /root/hp/.alloy-sensor1.alloy /etc/alloy/config.alloy
      systemctl enable alloy >/dev/null 2>&1; systemctl restart alloy; sleep 5
      printf "service=%s " "$(systemctl is-active alloy)"
      curl -s -m 8 http://127.0.0.1:12345/-/ready >/dev/null 2>&1 && printf "ui=ready" || printf "ui=pending"
      echo
      ;;
    sensor2)
      incus file push --project lumi "/root/hp/.alloy-sensor2.alloy" prod-uk:sensor2/root/hp/.alloy-sensor2.alloy >/dev/null 2>&1
      incus exec --project lumi prod-uk:sensor2 -- bash -c "$(printf '%s' "$INSTALL")" 2>&1 | tr -d '\n'
      printf " | "
      incus exec --project lumi prod-uk:sensor2 -- bash -c "$(activate_cmd /root/hp/.alloy-sensor2.alloy)" 2>&1 | tr -d '\n'
      echo
      ;;
    *)
      scp -q -o BatchMode=yes "/root/hp/.alloy-$n.alloy" "root@$n:/root/hp/.alloy-$n.alloy" 2>/dev/null
      timeout 400 ssh -o BatchMode=yes "root@$n" "$(printf '%s' "$INSTALL")" 2>&1 | tr -d '\n'
      printf " | "
      timeout 150 ssh -o BatchMode=yes "root@$n" "$(activate_cmd "/root/hp/.alloy-$n.alloy")" 2>&1 | tr -d '\n'
      echo
      ;;
  esac
done

echo
echo "=== cleanup: the token now lives only where it is needed ==="
rm -f /root/hp/.alloy-*.alloy
for n in $NODES; do
  case "$n" in
    sensor1) : ;;
    sensor2) timeout 40 incus exec --project lumi prod-uk:sensor2 -- bash -c 'rm -f /root/hp/.alloy-*.alloy /root/hp/alloy-token; chown root:alloy /etc/alloy/config.alloy; chmod 640 /etc/alloy/config.alloy' >/dev/null 2>&1 ;;
    *) timeout 40 ssh -o BatchMode=yes "root@$n" 'rm -f /root/hp/.alloy-*.alloy /root/hp/alloy-token; chown root:alloy /etc/alloy/config.alloy; chmod 640 /etc/alloy/config.alloy' >/dev/null 2>&1 ;;
  esac
done
echo "  done — /etc/alloy/config.alloy per node (640 root:alloy) + /root/hp/alloy-token on sensor1"
echo
echo "=== next: query prometheus for up{job=\"node\"} to prove arrival ==="